//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformer
    {
        public int id { get; set; }
        public string TestId { get; set; }
        public Nullable<double> RatedVoltage { get; set; }
        public string RatedCapacity { get; set; }
        public string WindingGroup { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
        public string TestLocation { get; set; }
        public string Tester { get; set; }
        public Nullable<double> Frequency { get; set; }
        public Nullable<double> Volate { get; set; }
        public Nullable<double> currentnum { get; set; }
        public string DatagridData { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TestKind { get; set; }
    }
}
